---
# redis
spring:
  #  redis:
  #    database: 0
  #    host: 101.132.156.30
  #    port: 6379
  #    password: zL3kv59nv]st73Mm

  # MySQL数据源配置
  datasource:
    username:root
    password:1234567
    driver-class-name = com.mysql.cj.jdbc.Driver
    uri:jdbc:mysql://106.54.134.159:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    customer:
#      uri: "mongodb://root:root@101.132.156.30:27017/db_customer?authSource=admin"
#    device:
#      uri: "mongodb://root:root@101.132.156.30:27017/db_device2?authSource=admin"
#    system:
#      uri: "mongodb://root:root@101.132.156.30:27017/db_system?authSource=admin"


# 日志配置
#logging:
#  level:
#    root: INFO
#    com.fwiot.skywalker: DEBUG
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

